### ISSUE TITLE
gpmdp-cli.py: error: unrecognized arguments: {second command}

### ISSUE THREAD

**Issue by JAicewizard** [Glitch-is/gpmdp-cli#1]
when I try to run this script the line `args = parser.parse_args()` print out:
gpmdp-cli.py: error: unrecognized arguments: {second command}
if I try to use only one argument it returns it rives a out of range error, as to be expected, on line 75.

Connected to client!
Traceback (most recent call last):
  File "gpmdp-cli.py", line 105, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "gpmdp-cli.py", line 88, in main
    await sendCommand(websocket, parseCommands(commands))
  File "gpmdp-cli.py", line 75, in parseCommands
    payload["method"] = c[1]
IndexError: list index out of range

**Comment by Glitch-is** [comment]
What's the exact command you're trying to run?

**Comment by JAicewizard** [comment]
In this case 
python3 gpmdp-cli.py playback playPause
But any set off commands fails.
Ive als tried to use ./gpmdp-cli... With any success

**Comment by JAicewizard** [comment]
I mean without any success, I shouldn't do things like this on my phone.

**Comment by Glitch-is** [comment]
It appears that the examples documented in the README file are slightly wrong.
Try doing
```
python3 gpmdp-cli.py "playback playPause"
```

I'll fix the examples

**Comment by JAicewizard** [comment]
thanks it works now as expected,
